### ISSUE TITLE
Breed should be a dropdown and not a textfield. If you want a new breed there should be an option to add it via the breed page

### ISSUE THREAD

**Issue by lanza** [ETLanza/DogsBestFriend#35]

**Comment by ETLanza** [comment]
If this is referring to the "Add Dog" page, it is like this for simplicity of use.  If I wanted to add in a Whippet, I would be annoyed if I had to scroll down past 200 other breed names just to enter Whippet. It also allows for the user to sub breed if they feel so inclined, such as "Goldendoodle 2B"
